# Generated by Django 5.2.7 on 2025-10-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_staff_qr_code_attendance_status_staff_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Signed In', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
