# Generated by Django 5.2.7 on 2025-10-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_staff_barcode_image_staff_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='barcode_image',
        ),
        migrations.AddField(
            model_name='staff',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
