# Generated by Django 5.2.7 on 2025-11-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_remove_staff_barcode_image_staff_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
