# Generated by Django 5.2.7 on 2025-11-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_staff_date_joined_alter_staff_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
