# Generated by Django 5.2.7 on 2025-11-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_remove_staff_date_joined_alter_staff_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Late', 'Late'), ('Signed Out', 'Signed Out'), ('Absent', 'Absent')], max_length=20, null=True),
        ),
    ]
