# Generated by Django 5.2.7 on 2025-11-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Signed In', 'Signed In'), ('Signed Out', 'Signed Out'), ('On Time', 'On Time'), ('Late', 'Late'), ('Absent', 'Absent')], default='Signed In', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
