# Generated by Django 5.2.7 on 2025-11-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_attendance_date_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Signed In', 'Signed In'), ('Signed Out', 'Signed Out'), ('On Time', 'On Time'), ('Late', 'Late'), ('Absent', 'Absent')], default='Signed In', max_length=25),
        ),
    ]
